"""Catalogos funcionales de las secciones S01 y S02 del nivel 1.

Este archivo concentra la definicion parametrica del formulario para el
primer nivel de atencion. La estructura se mantiene explicita para que pueda
ser revisada y ajustada sin recorrer SQL complejo.
"""

from __future__ import annotations


SECCIONES = [
    {
        "codigo": "s01",
        "nombre": "Datos Generales",
        "descripcion": "Identificacion institucional del establecimiento de salud.",
        "orden": 1,
    },
    {
        "codigo": "s02",
        "nombre": "Acceso y Movilizacion",
        "descripcion": "Caracteristicas de acceso, movilidad, tiempo de traslado y tipo de via.",
        "orden": 2,
    },
]


VARIABLES = [
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg01",
        "etiqueta": "Unicodigo",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 1,
        "validacion_json": {"max_length": 20, "fuente": "vm_establecimientos_ingresados.uni_codigo"},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg02",
        "etiqueta": "Establecimiento de Salud",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 2,
        "validacion_json": {"max_length": 255},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg03",
        "etiqueta": "Tipologia",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 3,
        "validacion_json": {"max_length": 150},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg04",
        "etiqueta": "Institucion",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 4,
        "validacion_json": {"max_length": 150},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg05",
        "etiqueta": "Direccion Provincial",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 5,
        "validacion_json": {"max_length": 150},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg06",
        "etiqueta": "Canton",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 6,
        "validacion_json": {"max_length": 150},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg07",
        "etiqueta": "Parroquia",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 7,
        "validacion_json": {"max_length": 150},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg08",
        "etiqueta": "Direccion del Establecimiento",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 8,
        "validacion_json": {"max_length": 255},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg09",
        "etiqueta": "Permiso de funcionamiento",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 9,
        "validacion_json": {"max_length": 150},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg10",
        "etiqueta": "Estado del predio",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 10,
        "validacion_json": {"max_length": 150},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg11",
        "etiqueta": "Nombres completos del Responsable",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 11,
        "validacion_json": {"max_length": 255},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg12",
        "etiqueta": "Movil del Responsable",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 12,
        "validacion_json": {"max_length": 30},
        "opciones": [],
    },
    {
        "seccion_codigo": "s01",
        "codigo": "s01_dg13",
        "etiqueta": "Cedula de identidad del Responsable",
        "tipo_control": "text",
        "tipo_dato": "texto",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 13,
        "validacion_json": {"max_length": 20},
        "opciones": [],
    },
    {
        "seccion_codigo": "s02",
        "codigo": "s02_am01",
        "etiqueta": "Frontera",
        "tipo_control": "radio",
        "tipo_dato": "catalogo",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 1,
        "validacion_json": {"tipo": "dicotomica", "valores_permitidos": ["Si", "No"]},
        "opciones": [
            (1, "Si", ""),
            (2, "No", ""),
        ],
    },
    {
        "seccion_codigo": "s02",
        "codigo": "s02_am02",
        "etiqueta": "Medio de movilizacion",
        "tipo_control": "select",
        "tipo_dato": "catalogo",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 2,
        "validacion_json": {"tipo": "catalogo"},
        "opciones": [
            (1, "Terrestre", "Alta accesibilidad"),
            (2, "Fluvial", "Media accesibilidad"),
            (3, "Aereo", "Baja accesibilidad"),
        ],
    },
    {
        "seccion_codigo": "s02",
        "codigo": "s02_am03",
        "etiqueta": "Frecuencia del transporte publico",
        "tipo_control": "select",
        "tipo_dato": "catalogo",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 3,
        "validacion_json": {"tipo": "catalogo"},
        "opciones": [
            (1, "Diaria", "Alta accesibilidad"),
            (2, "Dos veces al dia", "Media accesibilidad"),
            (3, "Una a dos veces por semana", "Baja accesibilidad"),
            (4, "Nunca", "Muy baja accesibilidad"),
        ],
    },
    {
        "seccion_codigo": "s02",
        "codigo": "s02_am04",
        "etiqueta": "Tiempo hasta el Establecimiento de Salud",
        "tipo_control": "number",
        "tipo_dato": "decimal",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 4,
        "validacion_json": {
            "min": 1,
            "precision": 2,
            "regla_unidad": "Horas permite valores reales mayores o iguales a uno; Minutos permite valores reales entre uno y cincuenta y nueve.",
        },
        "opciones": [],
    },
    {
        "seccion_codigo": "s02",
        "codigo": "s02_am04_unidad",
        "etiqueta": "Unidad del tiempo de traslado",
        "tipo_control": "radio",
        "tipo_dato": "catalogo",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 5,
        "validacion_json": {"tipo": "unidad_tiempo", "valores_permitidos": ["Horas", "Minutos"]},
        "opciones": [
            (1, "Horas", ""),
            (2, "Minutos", ""),
        ],
    },
    {
        "seccion_codigo": "s02",
        "codigo": "s02_am05",
        "etiqueta": "Categoria de accesibilidad",
        "tipo_control": "radio",
        "tipo_dato": "catalogo",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 6,
        "validacion_json": {"tipo": "dicotomica_territorial", "valores_permitidos": ["Urbano", "Rural"]},
        "opciones": [
            (1, "Urbano", "Alta accesibilidad"),
            (2, "Rural", "Media accesibilidad"),
        ],
    },
    {
        "seccion_codigo": "s02",
        "codigo": "s02_am06",
        "etiqueta": "Tipo de via",
        "tipo_control": "select",
        "tipo_dato": "catalogo",
        "unidad_medida": None,
        "obligatorio": True,
        "orden": 7,
        "validacion_json": {"tipo": "catalogo"},
        "opciones": [
            (1, "Primer orden", "Alta accesibilidad"),
            (2, "Segundo orden", "Media accesibilidad"),
            (3, "Tercer orden", "Baja accesibilidad"),
        ],
    },
]


VALIDACIONES = [
    ("s01_dg01", "fuente_institucional", "El unicodigo debe existir en la fuente institucional."),
    ("s02_am01", "catalogo_dicotomico", "Frontera debe registrarse con una opcion controlada: Si o No."),
    ("s02_am04", "rango_minimo", "El tiempo hasta el establecimiento de salud debe ser mayor o igual a uno."),
    (
        "s02_am04",
        "rango_por_unidad",
        "Si la unidad es Horas, el valor puede ser decimal mayor o igual a uno; si la unidad es Minutos, el valor debe estar entre uno y cincuenta y nueve.",
    ),
    ("s02_am04_unidad", "catalogo_unidad_tiempo", "La unidad del tiempo de traslado debe ser Horas o Minutos."),
    ("s02_am05", "catalogo_urbano_rural", "La categoria de accesibilidad debe ser Urbano o Rural."),
]
