# Generated by Django 6.1.1 on 2026-10-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigem', '0002_nivel_atencion_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablecimientoIngresado',
            fields=[
                ('uni_serial', models.TextField(primary_key=True, serialize=False)),
                ('uni_codigo', models.TextField()),
                ('uni_nombre', models.TextField(blank=True, null=True)),
                ('uni_direccion', models.TextField(blank=True, null=True)),
                ('prv_descripcion', models.TextField(blank=True, null=True)),
                ('can_descripcion', models.TextField(blank=True, null=True)),
                ('par_descripcion', models.TextField(blank=True, null=True)),
                ('dis_descripcion', models.TextField(blank=True, null=True)),
                ('tipologia', models.TextField(blank=True, null=True)),
                ('igu_descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('dificilacceso', models.TextField(blank=True, null=True)),
                ('establecimiento', models.TextField(blank=True, null=True)),
                ('nombre_comercial', models.TextField(blank=True, null=True)),
                ('represen_legal', models.TextField(blank=True, null=True)),
                ('tlf_movil', models.TextField(blank=True, null=True)),
                ('ced_ident_rep_legal', models.TextField(blank=True, null=True)),
                ('dp_descripcion', models.TextField(blank=True, null=True)),
                ('nivel_atencion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Establecimiento ingresado',
                'verbose_name_plural': 'Establecimientos ingresados',
                'db_table': 'vm_establecimientos_ingresados',
                'managed': False,
            },
        ),
    ]
